# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dlg.ui'
#
# Created: Sun Apr 10 00:16:58 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_spcontroller(object):
    def setupUi(self, spcontroller):
        spcontroller.setObjectName(_fromUtf8("spcontroller"))
        spcontroller.setEnabled(True)
        spcontroller.resize(333, 415)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(spcontroller.sizePolicy().hasHeightForWidth())
        spcontroller.setSizePolicy(sizePolicy)
        spcontroller.setMinimumSize(QtCore.QSize(0, 0))
        spcontroller.setSizeGripEnabled(False)
        spcontroller.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(spcontroller)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(spcontroller)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.main = QtGui.QWidget()
        self.main.setObjectName(_fromUtf8("main"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.main)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.statuxBox = QtGui.QGroupBox(self.main)
        self.statuxBox.setObjectName(_fromUtf8("statuxBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.statuxBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.statusFormLayout = QtGui.QFormLayout()
        self.statusFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.statusFormLayout.setHorizontalSpacing(12)
        self.statusFormLayout.setObjectName(_fromUtf8("statusFormLayout"))
        self.deviceLabel = QtGui.QLabel(self.statuxBox)
        self.deviceLabel.setObjectName(_fromUtf8("deviceLabel"))
        self.statusFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.deviceLabel)
        self.calibrationLabel = QtGui.QLabel(self.statuxBox)
        self.calibrationLabel.setObjectName(_fromUtf8("calibrationLabel"))
        self.statusFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.calibrationLabel)
        self.statusCalibration = QtGui.QLabel(self.statuxBox)
        self.statusCalibration.setText(_fromUtf8(""))
        self.statusCalibration.setObjectName(_fromUtf8("statusCalibration"))
        self.statusFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.statusCalibration)
        self.alignedLabel = QtGui.QLabel(self.statuxBox)
        self.alignedLabel.setObjectName(_fromUtf8("alignedLabel"))
        self.statusFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.alignedLabel)
        self.statusAligned = QtGui.QLabel(self.statuxBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusAligned.setFont(font)
        self.statusAligned.setText(_fromUtf8(""))
        self.statusAligned.setObjectName(_fromUtf8("statusAligned"))
        self.statusFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.statusAligned)
        self.statusDevice = QtGui.QLabel(self.statuxBox)
        self.statusDevice.setObjectName(_fromUtf8("statusDevice"))
        self.statusFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.statusDevice)
        self.horizontalLayout_5.addLayout(self.statusFormLayout)
        self.verticalLayout_4.addWidget(self.statuxBox)
        self.coordBox = QtGui.QGroupBox(self.main)
        self.coordBox.setFlat(False)
        self.coordBox.setCheckable(False)
        self.coordBox.setObjectName(_fromUtf8("coordBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.coordBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.coordsFormLayout = QtGui.QFormLayout()
        self.coordsFormLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.coordsFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.coordsFormLayout.setHorizontalSpacing(12)
        self.coordsFormLayout.setObjectName(_fromUtf8("coordsFormLayout"))
        self.targetLabel = QtGui.QLabel(self.coordBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.targetLabel.setFont(font)
        self.targetLabel.setScaledContents(False)
        self.targetLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.targetLabel.setObjectName(_fromUtf8("targetLabel"))
        self.coordsFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.targetLabel)
        self.coordTarget = QtGui.QLabel(self.coordBox)
        self.coordTarget.setObjectName(_fromUtf8("coordTarget"))
        self.coordsFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.coordTarget)
        self.currentLabel = QtGui.QLabel(self.coordBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentLabel.setFont(font)
        self.currentLabel.setObjectName(_fromUtf8("currentLabel"))
        self.coordsFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.currentLabel)
        self.coordCurrent = QtGui.QLabel(self.coordBox)
        self.coordCurrent.setObjectName(_fromUtf8("coordCurrent"))
        self.coordsFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.coordCurrent)
        self.axesLabel = QtGui.QLabel(self.coordBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.axesLabel.setFont(font)
        self.axesLabel.setObjectName(_fromUtf8("axesLabel"))
        self.coordsFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.axesLabel)
        self.coordAxes = QtGui.QLabel(self.coordBox)
        self.coordAxes.setObjectName(_fromUtf8("coordAxes"))
        self.coordsFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.coordAxes)
        self.verticalLayout_2.addLayout(self.coordsFormLayout)
        self.verticalLayout_4.addWidget(self.coordBox)
        self.controlBox = QtGui.QGroupBox(self.main)
        self.controlBox.setEnabled(True)
        self.controlBox.setObjectName(_fromUtf8("controlBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.controlBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.laserButton = QtGui.QPushButton(self.controlBox)
        self.laserButton.setEnabled(True)
        self.laserButton.setCheckable(True)
        self.laserButton.setAutoDefault(False)
        self.laserButton.setObjectName(_fromUtf8("laserButton"))
        self.verticalLayout_3.addWidget(self.laserButton)
        self.gotoButton = QtGui.QPushButton(self.controlBox)
        self.gotoButton.setEnabled(True)
        self.gotoButton.setAutoDefault(False)
        self.gotoButton.setObjectName(_fromUtf8("gotoButton"))
        self.verticalLayout_3.addWidget(self.gotoButton)
        self.alignButton = QtGui.QPushButton(self.controlBox)
        self.alignButton.setEnabled(False)
        self.alignButton.setAutoDefault(False)
        self.alignButton.setObjectName(_fromUtf8("alignButton"))
        self.verticalLayout_3.addWidget(self.alignButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.leftButton = QtGui.QPushButton(self.controlBox)
        self.leftButton.setEnabled(True)
        self.leftButton.setMinimumSize(QtCore.QSize(0, 0))
        self.leftButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-left"))
        self.leftButton.setIcon(icon)
        self.leftButton.setAutoDefault(False)
        self.leftButton.setObjectName(_fromUtf8("leftButton"))
        self.gridLayout_2.addWidget(self.leftButton, 1, 0, 1, 1)
        self.downButton = QtGui.QPushButton(self.controlBox)
        self.downButton.setEnabled(True)
        self.downButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-down"))
        self.downButton.setIcon(icon)
        self.downButton.setAutoDefault(False)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.gridLayout_2.addWidget(self.downButton, 2, 1, 1, 1)
        self.rightButton = QtGui.QPushButton(self.controlBox)
        self.rightButton.setEnabled(True)
        self.rightButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-right"))
        self.rightButton.setIcon(icon)
        self.rightButton.setCheckable(False)
        self.rightButton.setAutoRepeat(False)
        self.rightButton.setAutoExclusive(False)
        self.rightButton.setAutoDefault(False)
        self.rightButton.setObjectName(_fromUtf8("rightButton"))
        self.gridLayout_2.addWidget(self.rightButton, 1, 2, 1, 1)
        self.upButton = QtGui.QPushButton(self.controlBox)
        self.upButton.setEnabled(True)
        self.upButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-up"))
        self.upButton.setIcon(icon)
        self.upButton.setAutoDefault(False)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.gridLayout_2.addWidget(self.upButton, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addWidget(self.controlBox)
        self.tabWidget.addTab(self.main, _fromUtf8(""))
        self.points = QtGui.QWidget()
        self.points.setObjectName(_fromUtf8("points"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.points)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.newPointButton = QtGui.QPushButton(self.points)
        self.newPointButton.setEnabled(False)
        self.newPointButton.setObjectName(_fromUtf8("newPointButton"))
        self.horizontalLayout_2.addWidget(self.newPointButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.saveButton = QtGui.QPushButton(self.points)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.textPoints = QtGui.QTextEdit(self.points)
        self.textPoints.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textPoints.setReadOnly(False)
        self.textPoints.setObjectName(_fromUtf8("textPoints"))
        self.verticalLayout_7.addWidget(self.textPoints)
        self.tabWidget.addTab(self.points, _fromUtf8(""))
        self.config = QtGui.QWidget()
        self.config.setObjectName(_fromUtf8("config"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.config)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.configFormLayout = QtGui.QFormLayout()
        self.configFormLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.configFormLayout.setHorizontalSpacing(12)
        self.configFormLayout.setObjectName(_fromUtf8("configFormLayout"))
        self.serialPortLabel = QtGui.QLabel(self.config)
        self.serialPortLabel.setObjectName(_fromUtf8("serialPortLabel"))
        self.configFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.serialPortLabel)
        self.serialCombo = QtGui.QComboBox(self.config)
        self.serialCombo.setObjectName(_fromUtf8("serialCombo"))
        self.configFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.serialCombo)
        self.joystickLabel = QtGui.QLabel(self.config)
        self.joystickLabel.setObjectName(_fromUtf8("joystickLabel"))
        self.configFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.joystickLabel)
        self.joystickCombo = QtGui.QComboBox(self.config)
        self.joystickCombo.setEnabled(False)
        self.joystickCombo.setObjectName(_fromUtf8("joystickCombo"))
        self.joystickCombo.addItem(_fromUtf8(""))
        self.configFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.joystickCombo)
        self.enableServerLabel = QtGui.QLabel(self.config)
        self.enableServerLabel.setObjectName(_fromUtf8("enableServerLabel"))
        self.configFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.enableServerLabel)
        self.enableServer = QtGui.QCheckBox(self.config)
        self.enableServer.setObjectName(_fromUtf8("enableServer"))
        self.configFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.enableServer)
        self.serverPortLabel = QtGui.QLabel(self.config)
        self.serverPortLabel.setObjectName(_fromUtf8("serverPortLabel"))
        self.configFormLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.serverPortLabel)
        self.serverPort = QtGui.QSpinBox(self.config)
        self.serverPort.setMinimum(10000)
        self.serverPort.setMaximum(11000)
        self.serverPort.setObjectName(_fromUtf8("serverPort"))
        self.configFormLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.serverPort)
        self.localHostOnlyLabel = QtGui.QLabel(self.config)
        self.localHostOnlyLabel.setObjectName(_fromUtf8("localHostOnlyLabel"))
        self.configFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.localHostOnlyLabel)
        self.localHostOnly = QtGui.QCheckBox(self.config)
        self.localHostOnly.setChecked(True)
        self.localHostOnly.setObjectName(_fromUtf8("localHostOnly"))
        self.configFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.localHostOnly)
        self.verticalLayout_5.addLayout(self.configFormLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.calibrateButton = QtGui.QPushButton(self.config)
        self.calibrateButton.setEnabled(False)
        self.calibrateButton.setAutoDefault(False)
        self.calibrateButton.setObjectName(_fromUtf8("calibrateButton"))
        self.horizontalLayout_3.addWidget(self.calibrateButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.applyButton = QtGui.QPushButton(self.config)
        self.applyButton.setAutoDefault(False)
        self.applyButton.setDefault(True)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout_3.addWidget(self.applyButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.config, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(spcontroller)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(spcontroller)
        spcontroller.setTabOrder(self.laserButton, self.gotoButton)
        spcontroller.setTabOrder(self.gotoButton, self.upButton)
        spcontroller.setTabOrder(self.upButton, self.rightButton)
        spcontroller.setTabOrder(self.rightButton, self.downButton)
        spcontroller.setTabOrder(self.downButton, self.leftButton)

    def retranslateUi(self, spcontroller):
        spcontroller.setWindowTitle(_translate("spcontroller", "SkyPointer", None))
        self.statuxBox.setTitle(_translate("spcontroller", "Status", None))
        self.deviceLabel.setText(_translate("spcontroller", "Device:", None))
        self.calibrationLabel.setText(_translate("spcontroller", "Calibration:", None))
        self.alignedLabel.setText(_translate("spcontroller", "Aligned:", None))
        self.statusDevice.setText(_translate("spcontroller", "Not connected", None))
        self.coordBox.setTitle(_translate("spcontroller", "Coordinates", None))
        self.targetLabel.setText(_translate("spcontroller", "Target:", None))
        self.currentLabel.setText(_translate("spcontroller", "Current:", None))
        self.axesLabel.setText(_translate("spcontroller", "Axes:", None))
        self.controlBox.setTitle(_translate("spcontroller", "Control", None))
        self.laserButton.setText(_translate("spcontroller", "Laser", None))
        self.laserButton.setShortcut(_translate("spcontroller", "L", None))
        self.gotoButton.setText(_translate("spcontroller", "Go to...", None))
        self.gotoButton.setShortcut(_translate("spcontroller", "G", None))
        self.alignButton.setText(_translate("spcontroller", "Align", None))
        self.alignButton.setShortcut(_translate("spcontroller", "A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("spcontroller", "&Main", None))
        self.newPointButton.setText(_translate("spcontroller", "New point", None))
        self.newPointButton.setShortcut(_translate("spcontroller", "N", None))
        self.saveButton.setText(_translate("spcontroller", "Save...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.points), _translate("spcontroller", "&Points", None))
        self.serialPortLabel.setText(_translate("spcontroller", "Serial port:", None))
        self.joystickLabel.setText(_translate("spcontroller", "Joystick:", None))
        self.joystickCombo.setItemText(0, _translate("spcontroller", "None", None))
        self.enableServerLabel.setText(_translate("spcontroller", "Enable server", None))
        self.serverPortLabel.setText(_translate("spcontroller", "Server port:", None))
        self.localHostOnlyLabel.setText(_translate("spcontroller", "Local host only", None))
        self.calibrateButton.setText(_translate("spcontroller", "Calibrate...", None))
        self.applyButton.setText(_translate("spcontroller", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config), _translate("spcontroller", "&Configuration", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    spcontroller = QtGui.QDialog()
    ui = Ui_spcontroller()
    ui.setupUi(spcontroller)
    spcontroller.show()
    sys.exit(app.exec_())

